# Generated by Django 5.2.1 on 2025-06-05 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('modell', models.CharField(max_length=100)),
                ('stock', models.BooleanField(default=True)),
                ('price', models.DecimalField(decimal_places=2, default=30.0, max_digits=10)),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('radius', models.IntegerField()),
                ('cameraX', models.IntegerField()),
                ('cameraY', models.IntegerField()),
                ('cameraWidth', models.IntegerField()),
                ('cameraHeight', models.IntegerField()),
                ('cameraRadius', models.IntegerField()),
                ('url', models.URLField()),
                ('bwidth', models.IntegerField(blank=True, null=True)),
                ('bheight', models.IntegerField(blank=True, null=True)),
                ('sku', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('type', 'modell')},
            },
        ),
    ]
