# Generated by Django 5.2.1 on 2025-06-05 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_phoneproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phoneproduct',
            name='bheight',
        ),
        migrations.RemoveField(
            model_name='phoneproduct',
            name='bwidth',
        ),
        migrations.RemoveField(
            model_name='phoneproduct',
            name='cameraHeight',
        ),
        migrations.RemoveField(
            model_name='phoneproduct',
            name='cameraRadius',
        ),
        migrations.RemoveField(
            model_name='phoneproduct',
            name='cameraWidth',
        ),
        migrations.RemoveField(
            model_name='phoneproduct',
            name='cameraX',
        ),
        migrations.RemoveField(
            model_name='phoneproduct',
            name='cameraY',
        ),
        migrations.RemoveField(
            model_name='phoneproduct',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='phoneproduct',
            name='height',
        ),
        migrations.RemoveField(
            model_name='phoneproduct',
            name='radius',
        ),
        migrations.RemoveField(
            model_name='phoneproduct',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='phoneproduct',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='phoneproduct',
            name='url',
        ),
        migrations.RemoveField(
            model_name='phoneproduct',
            name='width',
        ),
        migrations.RemoveField(
            model_name='phoneproduct',
            name='x',
        ),
        migrations.RemoveField(
            model_name='phoneproduct',
            name='y',
        ),
        migrations.AlterField(
            model_name='phoneproduct',
            name='stock',
            field=models.CharField(max_length=100),
        ),
    ]
