# Generated by Django 5.2.1 on 2025-06-05 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_phoneproduct_bheight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneproduct',
            name='stock',
            field=models.BooleanField(default=True),
        ),
    ]
