# Generated by Django 5.2.1 on 2025-06-05 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_phoneproduct_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='phoneproduct',
            name='case_image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='phoneproduct',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
