# Generated by Django 5.2.1 on 2025-06-05 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_phoneproduct_case_image_url_phoneproduct_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phoneproduct',
            name='case_image_url',
        ),
        migrations.RemoveField(
            model_name='phoneproduct',
            name='image_url',
        ),
    ]
