# Generated by Django 5.2.1 on 2025-06-05 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_phoneproduct_case_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phoneproduct',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
