# Generated by Django 5.2.1 on 2025-06-08 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_customuser_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='suspension_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
