# Generated by Django 5.2.1 on 2025-06-08 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_customuser_suspension_end_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-publish_date', '-created_at']},
        ),
        migrations.AddField(
            model_name='announcement',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='announcement',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image')], default='text', max_length=10),
        ),
    ]
